# Generated by Django 3.1.2 on 2020-10-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(default='-', max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
